export const team = [
  {
    id: 1,
    name: "Ashwin Gaidhani",
    role: "CEO & Founder",
    image: "/images/team/Ashwin_CEO_1.png",
    linkedin: "https://linkedin.com/",
    slug: "ashwin-gaidhani",
  },
  {
    id: 2,
    name: "Yagnaseni Gaidhani",
    role: "CEO",
    image: "/images/team/member-2.jpg",
    linkedin: "https://linkedin.com/",
    slug: "yagnaseni-gaidhani",
  },
  {
    id: 3,
    name: "Ajas S",
    role: "Creative Director",
    image: "/images/team/Ajas.jpg",
    linkedin: "https://linkedin.com/",
    slug: "ajas-s",
  },
  {
    id: 4,
    name: "Libin Sharma",
    role: "Full Stack Web Developer",
    image: "/images/team/member-4.jpg",
    linkedin: "https://linkedin.com/",
    slug: "Libin Sharma",
  },
  {
    id: 5,
    name: "Jhanvi",
    role: "GTM Strategy",
    image: "/images/team/Janvi.jpg",
    linkedin: "https://linkedin.com/",
    slug: "Jhanvi",
  },
  {
    id: 6,
    name: "Shreya Gir",
    role: "Project Manager",
    image: "/images/team/Shreya_Gir.jpg",
    linkedin: "https://linkedin.com/",
    slug: "shreya-gir",
  },
  {
    id: 7,
    name: "Apoorva Rao",
    role: "Project Manager",
    image: "/images/team/Apoorva_Rao.jpg",
    linkedin: "https://linkedin.com/",
    slug: "shreya-gir",
  },
  {
    id: 8,
    name: "Harita",
    role: "Project Manager",
    image: "/images/team/Harita.jpg",
    linkedin: "https://linkedin.com/",
    slug: "shreya-gir",
  },
  {
    id: 9,
    name: "Meera",
    role: "Project Manager",
    image: "/images/team/Meera.jpg",
    linkedin: "https://linkedin.com/",
    slug: "shreya-gir",
  },
  {
    id: 10,
    name: "Subramani",
    role: "Project Manager",
    image: "/images/team/Subramani.jpg",
    linkedin: "https://linkedin.com/",
    slug: "shreya-gir",
  },
  {
    id: 11,
    name: "Nafeez_Al",
    role: "Project Manager",
    image: "/images/team/Nafeez_Al.jpg",
    linkedin: "https://linkedin.com/",
    slug: "shreya-gir",
  },
  {
    id: 12,
    name: "Tapati_CEO_2",
    role: "Project Manager",
    image: "/images/team/Tapati_CEO_2.png",
    linkedin: "https://linkedin.com/",
    slug: "shreya-gir",
  },
];